=== jbrazile/jjval/src/test/resources/products.dtd
<!ELEMENT products (product+)>
<!ELEMENT product (productId,productName,price?,tags?,dimensions?)>
<!ELEMENT productId (#PCDATA)>
<!ELEMENT productName (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT tags (tag+)>
<!ELEMENT tag (#PCDATA)>
<!ELEMENT dimensions (length,width,height)>
<!ELEMENT length (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT height (#PCDATA)>

=== jbrazile/jjval/src/test/resources/products.ok.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE products SYSTEM "products.dtd">
<products>
  <product>
    <productId>1</productId>
    <productName>An ice sculpture</productName>
    <price>12.5</price>
    <tags>
      <tag>cold</tag>
      <tag>ice</tag>
    </tags>
    <dimensions>
      <length>7</length>
      <width>12</width>
      <height>9.5</height>
    </dimensions>
  </product>
  <product>
    <productId>2</productId>
    <productName>A green door</productName>
    <price>12.5</price>
    <tags>
      <tag>home</tag>
      <tag>green</tag>
    </tags>
  </product>
</products>
